Add Aeotec ZW111-C EU firmware version 2.4
zwave-js/firmware-updates pull request #101
Opened 2023-12-22 15:39 UTC by larstobi

Add firmware upgrade for Aeotec Nano Dimmer ZW111-C EU version 2.04.

Firmware page:
https://aeotec.freshdesk.com/support/solutions/articles/6000198943-how-to-update-nano-dimmer-z-wave-firmware-

2023-12-22 17:54 UTC, AlCalzone reviewed
@Aeotec-ccheng can you review this please?

2023-12-22 17:56 UTC, larstobi commented
Is it the integrity of the zip-file or the .exe file that we want as the sha256 sum?

2023-12-22 18:03 UTC, AlCalzone commented
Z-Wave JS doesn't support zip files for firmware updates currently, so we'd need a link to the file contained in the ZIP.
If you run the URL through `npx @zwave-js/firmware-integrity <url>`, it will give you the correct integrity - if the file is in a supported format.

2023-12-22 18:06 UTC, larstobi commented
> Z-Wave JS doesn't support zip files for firmware updates currently, so we'd need a link to the file contained in the ZIP.

Aha. Since the file must be hosted by the manufacturer, and since the manufacturer has posted the file as a .zip file, then we cannot get this firmware to work with firmware-updates.

2023-12-22 19:10 UTC, Aeotec-ccheng commented
I'll see if i can grab the OTZ files, those can be used instead of the zip files we supply on that article. Hopefully should be able to get these files earlier next week after christmas (may not hear back until after new years).

2023-12-27 06:44 UTC, Aeotec-ccheng commented
https://aeotec.freshdesk.com/a/solutions/articles/6000198943 OTZ files posted in this link here @larstobi 

Specifically for EU Frequency, this should be the link here: https://aeotec.freshdesk.com/helpdesk/attachments/6189873103

Remember to generate a new SHA key.

2023-12-27 10:33 UTC, larstobi commented
Excellent! Thanks, will update the PR.

2023-12-28 07:17 UTC, Aeotec-ccheng commented
@AlCalzone this one should be good now. I'll make some for AU and US frequency once i get back to office on Jan 2nd.

2024-01-11 18:30 UTC, AlCalzone requested changes

2024-01-11 18:30 UTC, AlCalzone commented on firmwares/aeotec/ZW111-C.json
> +					"integrity": "sha256:165c1a652eeaf96c0d28370cd8480bf9bb3206dc9321e3d663b0de9d199a3082"
```suggestion
					"integrity": "sha256:aba71a9c6f2065b8fc5e683b81ebeea7cfbb1f66342be969d48eb5b671479b7e"
```

2024-01-11 18:31 UTC, AlCalzone approved these changes

2024-01-11 18:32 UTC, AlCalzone commented
Oh, I just saw the PR by @Aeotec-ccheng includes this one.

2024-01-11 18:33 UTC, closed without merging