files for: ZSE43, ZSE11, ZSE29, ZEN52, ZEN51, ZEN53
zwave-js/firmware-updates pull request #121
Opened 2024-04-17 18:50 UTC by TSHAdmin

2024-04-18 12:20 UTC, AlCalzone requested changes

2024-04-18 12:20 UTC, AlCalzone commented on firmwares/zooz/ZEN53,json
The filename here contains a comma instead of a dot.

2024-04-18 12:20 UTC, AlCalzone commented on firmwares/zooz/ZSE29-V2.json
> +			"changelog": "Includes firmware versions: 2.01, 2.2\n*  Improved Supervision Command Class which was affecting changing advanced parameters when the sensor was added with security on select platfo
Is this supposed to be version 2.2 or 2.20? The filename looks like it should be a 20.

2024-04-18 18:33 UTC, TSHAdmin commented on firmwares/zooz/ZSE29-V2.json
> +			"changelog": "Includes firmware versions: 2.01, 2.2\n*  Improved Supervision Command Class which was affecting changing advanced parameters when the sensor was added with security on select platfo
Yes, version 2.2 is valid.

2024-04-22 07:09 UTC, AlCalzone approved these changes

2024-04-22 07:09 UTC, merged