Add Aeotec ZW175-C EU firmware version 1.3
zwave-js/firmware-updates pull request #135
Opened 2024-08-09 09:47 UTC by mundschenk-at

This adds firmware 1.3 for the **EU version** of the **Aeotec Smart Switch 7** which was [recently made available](https://aeotec.freshdesk.com/support/solutions/articles/6000270359-update-smart-switch-7-eu-v1-03-zw175-c-). It fixes a rather annoying bug where the change threshold settings don't do anything when the initial value is above 0 (at least for the Watts sensor, though I'm not entirely sure other sensors were not affected as well).

@Aeotec-ccheng Could you please review this PR?

2024-08-09 19:06 UTC, Aeotec-ccheng requested changes
In the IF statement, you may need to change this statement:

"$if": "firmwareVersion < 1.3",
"version": "1.3",

to

"$if": "firmwareVersion < 1.3.1",
"version": "1.3.1",

Most ZW175-C units are already on V1.3.0 so it may not go through, need the 3rd decimal point to get it to others. Otherwise everything else looks good.

2024-08-09 20:14 UTC, mundschenk-at commented
> In the IF statement, you may need to change this statement:
> 
> "$if": "firmwareVersion < 1.3", "version": "1.3",
> 
> to
> 
> "$if": "firmwareVersion < 1.3.1", "version": "1.3.1",
> 
> Most ZW175-C units are already on V1.3.0 so it may not go through, need the 3rd decimal point to get it to others. Otherwise everything else looks good.

According to the [documentation](https://zwave-js.github.io/node-zwave-js/#/config-files/conditional-settings?id=conditional-configuration-settings), that is not necessary, patch number `0` is implied (i.e. `1.3.0` and `1.3` are equivalent for the comparison).

2024-08-09 20:37 UTC, Aeotec-ccheng commented
> > In the IF statement, you may need to change this statement:
> > "$if": "firmwareVersion < 1.3", "version": "1.3",
> > to
> > "$if": "firmwareVersion < 1.3.1", "version": "1.3.1",
> > Most ZW175-C units are already on V1.3.0 so it may not go through, need the 3rd decimal point to get it to others. Otherwise everything else looks good.
> 
> According to the [documentation](https://zwave-js.github.io/node-zwave-js/#/config-files/conditional-settings?id=conditional-configuration-settings), that is not necessary, patch number `0` is implied (i.e. `1.3.0` and `1.3` are equivalent for the comparison).
> 
> As for the current shipping firmware, I recently bought a large number of ZW175-C which were apparently shipped directly from Z-Wave Europe GmbH and so far all were on 1.2.

Ah ok, that was my misunderstanding and probably quickly glanced over it. This is fine then.

2024-08-09 20:37 UTC, Aeotec-ccheng approved these changes

2024-08-12 07:34 UTC, AlCalzone commented
Just to clarify, the `$if` statement is not required per se in this case. If a device is already on firmware 1.3, it won't be offered as an update.
What it achieves though is that the firmware will also not be offered to devices on higher versions as a downgrade. For example if there is a firmware 1.4 in the future and a user desires to downgrade to 1.3 for whatever reason, they won't be able to with the condition `firmwareVersion < 1.3`.

Not sure if that's what you intended @Aeotec-ccheng ?

2024-08-25 09:56 UTC, mundschenk-at commented
@Aeotec-ccheng Is it necessary to prevent downgrades?

2024-08-26 18:20 UTC, Aeotec-ccheng commented
@AlCalzone ah ok that makes sense - it isn't but if it can't be helped then that's fine. 

@mundschenk-at it isn't necessary to prevent downgrades, but in some cases downgrade of a specific version can cause bricking in some of our devices. This particular device doesn't care so much

2024-08-26 20:02 UTC, mundschenk-at commented
@AlCalzone Should I change the PR to allow downgrades?

2024-08-27 07:14 UTC, AlCalzone commented
IMO allowing users to downgrade where it is supported would be good.
After all, users can just download another version from the website anyways, but this service is more convenient and can add guardrails for the cases where users shouldn't downgrade.

2024-08-27 16:31 UTC, mundschenk-at commented
> IMO allowing users to downgrade where it is supported would be good. After all, users can just download another version from the website anyways, but this service is more convenient and can add guardrails for the cases where users shouldn't downgrade.

OK, I've removed the `$if` condition.

2024-08-29 08:21 UTC, AlCalzone commented
Thanks! I'll just need a final confirmation from @Aeotec-ccheng then I'll merge.

2024-08-29 20:38 UTC, AlCalzone approved these changes

2024-08-29 20:38 UTC, merged