Added stable version 1.57 for Inovelli LZW31-SN
zwave-js/firmware-updates pull request #24
Opened 2022-09-23 18:29 UTC by leojhartiv

2022-09-23 19:01 UTC, stu1811 commented
Target 1 should be https://files.inovelli.com/firmware/LZW31-SN/1.57/LZW31-SN_1.45.bin

2022-09-23 19:24 UTC, leojhartiv commented
> commented

Great catch!  Fixed!

2022-09-23 20:59 UTC, AlCalzone requested changes

2022-09-23 20:59 UTC, AlCalzone commented on firmwares/inovelli/LZW31-SN.json
> +			"changelog": "Fixed - Optimization of Aux mode in neutral setting. – Fixed - The inoperative issue after changing parameter 8 from high value to low value.",
```suggestion
			"changelog": "Fixed - Optimization of Aux mode in neutral setting.\nFixed - The inoperative issue after changing parameter 8 from high value to low value.",
```
Not sure if HA's renders this as markdown currently, but we should at least attempt to have a line break here.

2022-09-23 21:02 UTC, AlCalzone commented
Also, looks like the github action cannot post for forks, but the integrity hash is incorrect:

Error: **firmwares/inovelli/LZW31-SN.json**, version **1.57**, target **0**
Integrity hash mismatch
```diff
Expected: sha256:5c1d59906e302018c5c8bcd90040f0d545c8567a9c595a503df0ed27b77d5f33
Got:      sha256:c58d970e7148c000798e0bef3f214be4cbf93f62a784738e9b9c30b516b91e61
```

I guess this wasn't computed using the decoded HEX data:
> The integrity hash must be generated using the raw firmware data as it will be transferred to the device. If the firmware file is Intel HEX encoded or similar, this must be the hash of the decoded data. https://github.com/zwave-js/firmware-updates/blob/main/docs/firmware-files.md#defining-the-possible-upgrades-for-a-device

2022-09-26 13:57 UTC, leojhartiv commented
> Also, looks like the github action cannot post for forks, but the integrity hash is incorrect:
> 
> Error: **firmwares/inovelli/LZW31-SN.json**, version **1.57**, target **0** Integrity hash mismatch
> 
> ```diff
> Expected: sha256:5c1d59906e302018c5c8bcd90040f0d545c8567a9c595a503df0ed27b77d5f33
> Got:      sha256:c58d970e7148c000798e0bef3f214be4cbf93f62a784738e9b9c30b516b91e61
> ```
> 
> I guess this wasn't computed using the decoded HEX data:
> 
> > The integrity hash must be generated using the raw firmware data as it will be transferred to the device. If the firmware file is Intel HEX encoded or similar, this must be the hash of the decoded data. https://github.com/zwave-js/firmware-updates/blob/main/docs/firmware-files.md#defining-the-possible-upgrades-for-a-device

Thanks for the help with this!  Couldn't figure out why I was hashing wrong!

2022-09-26 15:05 UTC, AlCalzone commented
I've asked @InovelliUSA to check this, then we can merge.

2022-09-27 16:56 UTC, InovelliUSA commented
Looks good to me. I didn't check the hash's but it looks like they were reviewed by the community.

2022-09-27 18:26 UTC, AlCalzone approved these changes

2022-09-27 18:26 UTC, merged