Add v0.51 for 55258
zwave-js/firmware-updates pull request #36
Opened 2022-10-13 12:22 UTC by jascoproducts

Adding latest beta firmware for 55258.

2022-10-13 12:22 UTC, jascoproducts commented
New version link will need integrity hash added.

2022-10-13 14:11 UTC, AlCalzone commented
The tests don't show the expected hash. I guess that's because of the comment.

Can you generate it as described here?
https://github.com/zwave-js/firmware-integrity#usage

2022-10-13 17:32 UTC, AlCalzone commented
Not sure when I will be able to use a computer again, the little ones take almost all my time. You can try removing the comment `//`s and using a correctly formatted but incorrect integrity hash. Then the PR checks should show the correct one.

2022-10-14 09:01 UTC, AlCalzone commented
Looks good. Do you want to model the upgrade paths like on the draft PR or just keep it as is and have users on the 0.x version ignore the "update"

2022-10-14 15:15 UTC, jascoproducts commented
Just did. Hoping it works as intended.

2022-10-15 08:35 UTC, AlCalzone requested changes
You'll want to limit the existing 5.x entry to `firmwareVersion >= 5.0` (stable) and add another copy with the condition `firmwareVersion < 1.0` and beta channel to allow switching back.

The way it is now doesn't prevent the update to 5.x from being shown to 0.x users.

2022-10-15 10:23 UTC, AlCalzone commented
Sorry for the back and forth btw. If I had the time I'd do the changes myself.

2022-10-17 14:55 UTC, jascoproducts commented
Done! No worries. Still trying to figure this out.

2022-10-20 11:03 UTC, AlCalzone requested changes

2022-10-20 11:03 UTC, AlCalzone commented on firmwares/enbrighten-ge/ZW4002_55258.json
> +			"version": "5.50",
I'd add
```suggestion
			"version": "5.50",
			"channel": "beta",
```
so this doesn't permanently get shown as an update to the users of the alternate firmware.

2022-10-25 14:38 UTC, AlCalzone approved these changes

2022-10-25 14:38 UTC, merged